---
apiVersion: v1
kind: Service
metadata:
  name: skycast-app
  labels:
    app: skycast-app
spec:
  type: LoadBalancer
  selector:
    app: skycast-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
...
